### ISSUE TITLE
popover cannot hide right when page is very large

### ISSUE THREAD

**Issue by richal** [pleerock/ng2-popover#28]
when popover is hide, top = -1000, left = -1000, but sometimes page is very large, page size > 1000, so popover will display on left top position in window, could we change -1000 to -10000.

**Comment by SWortham** [comment]
I'm having the same issue. Richal's proposed solution of setting it to -10000px for both top and left instead would work and would be a quick and easy fix. 

If possible, setting display: none would be better but I'm guessing it wasn't done that way because of the need to calculate positioning based on the size of the popover. Seems like I've run into that when coding my own popovers.

**Comment by pleerock** [comment]
released in 0.0.11
